### ISSUE TITLE
Some notes about PAX setup steps

### ISSUE THREAD

**Issue by pietrobressana** [niksu/pax#19]
************************************************
"DEPENDENCIES" section under "BUILDING" section
************************************************

Please specify that:

- It's fine to use either Mono or Microsoft's C# compiler/runtime.

- We do use features specific to C# 6.0 however, and that's why a compiler for previous versions of C# can't be used.

- Therefore C# (>=6.0) compiler and runtime is required.

- The following setup steps have been tested on: Ubuntu 14.04.5, they should work fine on Ubuntu 16.10 too.

- After setting-up PAX, I have succesfully tested tallyer, dinger and wiring examples.

[1] RUN: sudo apt-get update AND sudo apt-get upgrade
[2] RUN: sudo apt-get install libpcap0.8
[3] Clone or download SharpPcap repository (https://github.com/chmorgan/sharppcap)
[4] Clone or download PacketDotNet repository (https://github.com/chmorgan/packetnet)
[5] Download one of Newtonsoft's JSON library releases (https://github.com/JamesNK/Newtonsoft.Json/releases)
[6] Clone or download PAX repository
[7] Install MONO by following the setup instructions (http://www.mono-project.com/docs/getting-started/install/linux/)
[OPTIONAL] RUN: sudo apt-get install mininet 

!!!!
THIS STEP IS IMPORTANT AND SHOULD BE HIGHLIGHTED, SINCE MANY *.dll FILES HAVE THE SAME NAME AND THE USER IS ASKED FOR REPLACING THEM.
!!!!
[8] Copy all *.dll files from Newtonsoft, SharpPcap and PacketDotNet folders into Pax's lib/ directory.(Replace files if asked while copying)

!!!!
THIS STEP SHOWS THAT NO DLLMAP CHANGE IS REQUIRED INTO MONO CONFIGURATION.
HOWEVER, THE PROVIDED "pax/lib/SharpPcap.dll.config" FILE MUST BE CHANGED AS FOLLOWS
IN ORDER TO POINT TO THE CORRECT "libpcap.so" LOCATION
!!!!		               
[9] DLLMAP
****************************
pax/lib/SharpPcap.dll.config
****************************
```
<configuration>
  <dllmap dll="wpcap" target="libpcap.dylib" os="osx" />
  <dllmap dll="wpcap" target="/usr/lib/x86_64-linux-gnu/libpcap.so.0.8" os="linux" />
</configuration>
```

**Comment by niksu** [comment]
Thanks very much for the feedback @pietrobressana 
I've opened a PR (https://github.com/niksu/pax/pull/21) to work on improving the build instructions. The current result can be see here: https://github.com/niksu/pax/blob/097f4e03cc95f959c74bad70b5c6233176459ccc/BUILD.md
To avoid overloading the README, I've extracted the build instructions into a separate file, leaving the README looking like this: https://github.com/niksu/pax/blob/097f4e03cc95f959c74bad70b5c6233176459ccc/README.md
Do these changes address your feedback, or can further improvements be made?

**Comment by niksu** [comment]
Thanks again for opening the issue. I'm closing it now after merging https://github.com/niksu/pax/pull/21, but do let me know it if anything further can be improved in the documentation.
